resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: europe-north1-docker.pkg.dev/knada-gcp/knada-north/orchestration-insight
  newTag: 4b2d2a2e689642a28e0a548356716776b05b3cea
