apiVersion: batch/v1
kind: CronJob
metadata:
  name: orchestration-insight
  namespace: knada-insight
  labels:
    job: knada-insight
spec:
  schedule: "0 8 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: orchestration-insight
          restartPolicy: Never
          containers:
          - name: orchestration-insight
            image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/orchestration-insight
